import Head from "next/head";
import { useEffect } from "react";
import { Fragment } from "react";
import Forest from "components/atoms/banners/forest/Forest";
import ThankSection from "components/molecules/thanks-section/ThankSection";
import axiosWooComerce from "utils/axiosWoocomerce";
import redirect from "nextjs-redirect";
import ScreenContainer from "components/atoms/container/screen-container/ScreenContainer";
import { CircularProgress } from "@material-ui/core";

const Redirect = redirect(process.env.HOME);

function Purchase(props) {
  useEffect(() => {
    console.log(props);
  }, []);

  if (props?.ticket?.id && props?.ticket?.status == "processing") {
    return (
      <Fragment>
        <Head>
          <title>Samgreen: thank you for your purchase</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.svg" />
        </Head>
        <Forest />
        <ThankSection ticket={props?.ticket} isMultiProduct={props?.isMultiProduct} />
      </Fragment>
    );
  } else {
    return (
      <Redirect>
        <ScreenContainer>
          <CircularProgress />
        </ScreenContainer>
      </Redirect>
    );
  }
}

Purchase.getInitialProps = async (ctx) => {
  let ticket = null;
  const id = ctx.query.purchase;
  try {
    const res = await axiosWooComerce.get(`${process.env.ORDERS}${id}`);
    ticket = res.data;
  } catch (err) {
    console.error(err);
  }

  return { ticket, isMultiProduct: ticket?.line_items.length > 1 };
};

export default Purchase;
