import Head from "next/head";
import { Fragment } from "react";
import Forest from "components/atoms/banners/forest/Forest";
import ThankSection from "components/molecules/thanks-section/ThankSection";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Samgreen: thank you for your purchase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Forest />
      <ThankSection />
    </Fragment>
  );
}
